services:
  app:
    restart: always
    image: docker.1ms.run/guog/hmi-ai-python:0.3.1
    ports:
      - "28090:8000"
    command:
      - fastapi
      - run
      #- --workers #--workers INTEGER 使用多个工作进程。与 --reload 标志互斥。[默认值：无]
      #- "4"
      - --reload #--reload 启用自动重新加载。仅在开发中使用。[默认值：无]
      - "app/main.py"
    volumes:
      - ./hollysys-hmi.pt:/hmi-ai-python/models/hollysys-hmi.pt
      - ./hollysys-hmi-line.pt:/hmi-ai-python/models/hollysys-hmi-line.pt
      - ./hmi-symbol-mapping.json:/hmi-ai-python/hmi-symbol-mapping.json
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/utils/health-check/"]
      interval: 10s
      timeout: 5s
      retries: 5
